# AUTO GENERATED FILE - DO NOT EDIT

from dash.development.base_component import Component, _explicitize_args


class DeckGL(Component):
    """A DeckGL component.
This component lets you visualizes PyDeck and deck/json files
directly in Dash. It also exposes various events (such as click,
hover and drag) inside callbacks.

Keyword arguments:
- data (dict | string; optional): Your map using the Deck.gl JSON format. This can be generated by calling
pdk.Deck(...).to_json(). Both a Python dictionary and a JSON-string your map is accepted.
- id (string; optional): The ID used to identify this component in Dash callbacks.
- mapboxKey (string; optional): `mapboxKey` (text): You will need a mapbox token to use deck.gl. Please create a mapbox
and follow the instructions here: https://docs.mapbox.com/help/how-mapbox-works/access-tokens/
- clickEvent (dict; optional): Read-only prop. This prop is updated when an element in the map is clicked. This contains
the original gesture event (in JSON).
- clickInfo (dict; optional): Read-only prop. This prop is updated when an element in the map is clicked. This contains
the picking info describing the object being clicked.

Complete description here:
https://deck.gl/docs/developer-guide/interactivity#the-picking-info-object
- hoverEvent (dict; optional): Read-only prop. This prop is updated when an element in the map is hovered. This contains
the original gesture event (in JSON).
- hoverInfo (dict; optional): Read-only prop. This prop is updated when an element in the map is hovered. This contains
the picking info describing the object being hovered.

Complete description here:
https://deck.gl/docs/developer-guide/interactivity#the-picking-info-object
- dragStartEvent (dict; optional): Read-only prop. This prop is updated when the user starts dragging on the canvas. This contains
the original gesture event (in JSON).
- dragStartInfo (dict; optional): Read-only prop. This prop is updated when the user starts dragging on the canvas. This contains
the picking info describing the object being dragged.

Complete description here:
https://deck.gl/docs/developer-guide/interactivity#the-picking-info-object
- dragEndEvent (dict; optional): Read-only prop. This prop is updated when the user releases from dragging the canvas. This contains
the original gesture event (in JSON).
- dragEndInfo (dict; optional): Read-only prop. This prop is updated when the user releases from dragging the canvas. This contains
the picking info describing the object being dragged.

Complete description here:
https://deck.gl/docs/developer-guide/interactivity#the-picking-info-object"""
    @_explicitize_args
    def __init__(self, data=Component.UNDEFINED, id=Component.UNDEFINED, mapboxKey=Component.UNDEFINED, clickEvent=Component.UNDEFINED, clickInfo=Component.UNDEFINED, hoverEvent=Component.UNDEFINED, hoverInfo=Component.UNDEFINED, dragStartEvent=Component.UNDEFINED, dragStartInfo=Component.UNDEFINED, dragEndEvent=Component.UNDEFINED, dragEndInfo=Component.UNDEFINED, **kwargs):
        self._prop_names = ['data', 'id', 'mapboxKey', 'clickEvent', 'clickInfo', 'hoverEvent', 'hoverInfo', 'dragStartEvent', 'dragStartInfo', 'dragEndEvent', 'dragEndInfo']
        self._type = 'DeckGL'
        self._namespace = 'dash_deck'
        self._valid_wildcard_attributes =            []
        self.available_properties = ['data', 'id', 'mapboxKey', 'clickEvent', 'clickInfo', 'hoverEvent', 'hoverInfo', 'dragStartEvent', 'dragStartInfo', 'dragEndEvent', 'dragEndInfo']
        self.available_wildcard_properties =            []

        _explicit_args = kwargs.pop('_explicit_args')
        _locals = locals()
        _locals.update(kwargs)  # For wildcard attrs
        args = {k: _locals[k] for k in _explicit_args if k != 'children'}

        for k in []:
            if k not in args:
                raise TypeError(
                    'Required argument `' + k + '` was not specified.')
        super(DeckGL, self).__init__(**args)
